Capstone.UI/Models/ViewModels.cs
using Capstone.Domain.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Capstone.UI.Models
{
    public class StockViewModel
    {
        public Company Company { get; set; }
        public string Search { get; set; }
    }
}

Capstone.UI/Controllers/CompanyController.cs
using Capstone.Domain.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Capstone.UI.Controllers
{
    public class CompanyController : Controller
    {
        //
        // GET: /Company/

        public ActionResult Details()
        {
            var symbol = Request["symb"].ToString();
            var context = new CapstoneContext();
            var model = context.Companies.Find(symbol);

            return View(model);
        }

    }
}

Capstone.UI/Controllers/HomeController.cs
using Capstone.Domain.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Capstone.UI.Controllers
{
    public class HomeController : Controller
    {

        public ActionResult Index()
        {
            var db = new CapstoneContext();

            var model = db.QStockPrices.GroupBy(q => q.CompanyId).Select(g => g.Key);

            return View(model);
        }

        public ActionResult GetSymbol()
        {
            var symbol = Request["symb"].ToString();

            var db = new CapstoneContext();

            var company = db.Companies.FirstOrDefault(e => e.StockId.Equals(symbol, StringComparison.OrdinalIgnoreCase));

            if (company != null)
            {
                @ViewBag.Response = company.CompanyName;
            }
            else
            {
                @ViewBag.Response = "Cannot find company";
            }
            return View("Index");
        }
    }
}

Capstone.UI/Controllers/StockChartController.cs
using Capstone.Domain.Models;
using Capstone.UI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Capstone.UI.Controllers
{
    public class StockChartController : Controller
    {
        //
        // GET: /StockChart/

        [HttpGet]
        public ActionResult Index(string id)
        {
            CapstoneContext context = new CapstoneContext();

            StockViewModel model = new StockViewModel();

            if (!string.IsNullOrEmpty(id))
            {
                model.Company = context.Companies.FirstOrDefault(c => c.StockId == id);
            }

            return View(model);
        }

        [HttpPost]
        public ActionResult Index(StockViewModel model)
        {
            if (model.Search != null)
            {
                CapstoneContext context = new CapstoneContext();

                model.Company = context.Companies.FirstOrDefault(c => c.StockId == model.Search);
            }

            return View(model);
        }
    }
}

Capstone.UI/Views/Company/Details.cshtml
@model Capstone.Domain.Models.Company
@{
    ViewBag.Title = "Details";
}
<h2>@Model.CompanyName</h2>
<div>
    <ul>
        @foreach (var news in Model.BingNews)
        {
            <li>
                <a href="@news.Url">@news.Title</a><span> @news.Date @news.Source</span>
            </li>
        }
    </ul>
</div>

Capstone.UI/Views/Home/Index.cshtml
@model IEnumerable<string>
@{
    ViewBag.Title = "Index";
}
<h2>Index</h2>
<div>
@*    @using(Html.BeginForm("GetSymbol", "Home"))
    {
        <div><label>Search for Symbol </label><input id="symb" name="symb" type="text" placeholder="AAPL"/><button type="submit" value="Submit">Search</button></div>
        <div><span>@ViewBag.Response</span></div>
    }*@
    <ul>
    @foreach (var s in Model)
    {
        <li>@Html.ActionLink(s, "Index", "StockChart", new { id = s }, null)</li>
    }
    </ul>
</div>

Capstone.UI/Views/Shared/_Layout.cshtml
<html>
    <head>
        <title>Capstone 11031782</title>
    </head>
<body>
        @using(Html.BeginForm("Details", "Company"))
        {
            <div><label>Search for Symbol </label><input id="symb" name="symb" type="text" placeholder="AAPL"/><button type="submit" value="Submit">Search</button></div>
        }
<section id="main">
@RenderBody()
</section>
</body>
</html>

Capstone.UI/Views/StockChart/Index.cshtml
@model Capstone.UI.Models.StockViewModel
@{
    ViewBag.Title = "Index";

    WebGrid grid = new WebGrid();
    if(Model.Company !=null)
    {
        grid = new WebGrid(Model.Company.QStockPrice.Reverse(), canPage: false, canSort:false);
    }
}

@using (Html.BeginForm("Index", "StockChart"))
{
    <div>
        @Html.TextBoxFor(m => m.Search)
        <input type="submit" value="Search"/>
    </div>
    <div>
@*        <ul>
        @foreach (var p in Model.Company.QStockPrice)
        {
            <li>Date: @p.Date.ToShortDateString() Open: @p.Open Closed @p.Close</li>
        }
        </ul>*@
    @if(Model.Company !=null)
    {
        @(grid.GetHtml(columns: 
        new []
        {
            grid.Column("date", "Date",format: @<div>@item.Date.ToShortDateString()</div>),
            grid.Column("Open", "Open"),
            grid.Column("Close", "Close")
        
        }))
    }
    </div>
}